### ISSUE TITLE
Expose inverse to `parseDiff`?

### ISSUE THREAD

**Issue by bgwines** [mulby/diff-parse#8]
Hi, there -- do you have any plans to expose some function like `unparseDiff :: FileDeltas -> Either String Text`? I'd like to use your library for a package but need such a function. Thanks so much!

**Comment by bgwines** [comment]
(yes, it's not a complete inverse because of which side the `Either`s are on, but you get the idea ;))

**Comment by bgwines** [comment]
Perhaps you wouldn't need the `Either` in returntype if all `FileDeltas` are well-formed or something.

**Comment by mulby** [comment]
I hadn't planned on writing a function like that, but would welcome the contribution if you wrote it.

**Comment by bgwines** [comment]
Ended up needing some other functionality so I wrote https://hackage.haskell.org/package/filediff instead, but it really solves a different problem so it and `ParseDiff` are complementary :)

**Comment by mulby** [comment]
Seems reasonable. Closing.
