### ISSUE TITLE
Version restriction on hspec seems too narrow

### ISSUE THREAD

**Issue by peti** [mulby/diff-parse#9]
Is there any particular reason why diff-parse doesn't allow building with [current versions of hspec](http://packdeps.haskellers.com/feed?needle=diff-parse)?

**Comment by mulby** [comment]
No particular reason, if you've tested it and it works, feel free to submit a PR that expands the range.

**Comment by peti** [comment]
I haven't tested it. I just noticed the build error when trying to distribute the package in NixOS.
